# Welcome to Facerec!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Facerec
description: A tutorial of how I built face unlock for Ubuntu Linux and how you can install that in your system as well.
github_username: rushabh-v

# Email and twitter are optional
email: vasanirushabh24@gmail.com
twitter_username: rushabh_24

# Set this to true to get LaTeX math equation support
use_math: 

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
